### ISSUE TITLE
Thoughts about texture/image support?

### ISSUE THREAD

**Issue by gingerbeardman** [edemaine/fold#23]
Just wondering where in the workflow texture/image could be introduced?

Ideally I would be folding an image in a particular way, less than a handful of distinct non-overlapping folds. So, not very complicated origami.

Obviously the image would have to be supported by the fold renderer, but perhaps it could be included as meta data. There would probably need to be both back and front images defined.

Thoughts appreciated.

**Comment by edemaine** [comment]
I've done some experiments with the following workflow:
* Fold a crease pattern (FOLD or SVG format) via [Origami Simulator](https://origamisimulator.org)
* Export OBJ
* Load in CAD software (e.g. Rhino)
* Apply texture image for the piece of paper

It works really well! (Thanks to OBJ export having texture coordinates.)  Is this what you're looking for?  If not, happy to discuss further.

**Comment by gingerbeardman** [comment]
Thanks!

Kind of. 

I was hoping to use a web-based based renderer. Exactly what I'm not sure but I'd want to animate the folding of "printed" material. 

Will give it some thought.

**Comment by edemaine** [comment]
If you want to animate, Origami Simulator is probably the way to go.  [This existing issue](https://github.com/amandaghassaei/OrigamiSimulator/issues/13) suggests adding texture support to the web-based renderer.  I'm going to close this issue in favor of that one.
