### ISSUE TITLE
Discrepancy about ordering of faces_edges between spec and example

### ISSUE THREAD

**Issue by cryslith** [edemaine/fold#37]
From the spec:

`faces_vertices` and `faces_edges` should align in start so that `faces_edges[f][i]` is the edge connecting `faces_vertices[f][i]` and `faces_vertices[f][(i+1)%d]` where `d` is the degree of face `f`.

The [diagonal-cp](https://github.com/edemaine/fold/blob/main/examples/diagonal-cp.fold) and [diagonal-folded](https://github.com/edemaine/fold/blob/main/examples/diagonal-folded.fold) examples violate this rule; these are the only examples which contain `faces_edges`.  They say they were created with Crease Pattern Editor, so maybe this is a bug in that tool?

**Comment by cryslith** [comment]
I think [this branch](https://github.com/edemaine/fold/compare/main...cryslith:lily/fix-faces-edges-order) should fix the issue in CP-Editor, but I can't manage to build the FOLD library to check.

**Comment by edemaine** [comment]
Finally merged this and released in 0.11.4.
