### ISSUE TITLE
Convert source from CoffeeScript to JavaScript or TypeScript or Civet?

### ISSUE THREAD

**Issue by mayakraft** [edemaine/fold#45]
Just wanted to throw this out there to gauge a response:

**Can we convert the `src/` folder from coffee script into ES6 Javascript or Typescript?**

This would be for the sole purpose of getting more code contributions from the community. If it resulted in no increase in contribution activity I would feel like I wasted everyone's time. Can we leave this issue open for a while, and if anyone has feelings about this would you like to leave a response?

1,300-1,700 lines of coffee script code, no tests to port.

**Comment by robbykraft** [comment]
Personally, I think ES6 Javascript (with JSDoc style comments) over Typescript for a few reasons:

- simpler build tooling
- strong types slow down development time
- the flexibility it allows for projects in exploratory phases

Rich Harris took the words out of my mouth recently. [link](https://devclass.com/2023/05/11/typescript-is-not-worth-it-for-developing-libraries-says-svelte-author-as-team-switches-to-javascript-and-jsdoc/)

**Comment by edemaine** [comment]
Related to #25 which we should definitely do one way or another. 

Personally I'd rather go in the other direction and port to [Civet](https://civet.dev). This would be an easier transition (as it's mostly CoffeeScript compatible), and because it's largely TypeScript compatible (most shorthand is optional), *maybe* it would be better for others contributing? (Not sure - it still might be intimidating.)

**Comment by robbykraft** [comment]
That's cool. in that case, Civet might be the best solution concerning types and ease of translation. Not sure I would bet on it if the aim is to increase community contributions. In that case I might still push for JS/TS as the safer bet. But, again, whatever people think! happy to hear more thoughts.

**Comment by MuTsunTsai** [comment]
If the motivation is to invite more contribution, I will certainly recommend TypeScript over alternatives. TypeScript is the de facto standard of JS development, while Civet is, to be honest, almost never discussed within the JS community, despite the hard work by @edemaine. Some numbers to support my point:
https://npmtrends.com/@danielx/civet-vs-coffeescript-vs-typescript

**Comment by mayakraft** [comment]
I notice this happened on another thread. thanks for the help @Mokshit06 !
